name: Build Docker Image

# See build results at
# https://github.com/RobCannon/k8-api-proxy/actions

# This workflow is triggered on pushes with a version tag to repository.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    # Job name is Greeting
    name: Docker Build

    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t k8s-api-proxy .

      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: k8-api-proxy # Provide only Docker image name
          extract-git-tag: true # Provide flag to extract Docker image tag from git reference
